import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Baby, BriefcaseBusiness, Car, Heart, PartyPopper, Sparkles, Sun, UtensilsCrossed, Users, Waves, Wifi } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { amenityCategories, facilityFeatures, facilityHero } from "@/data/facilities";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata = { title: "Facilities & Amenities", description: "Explore the conceptual facilities and amenities imagined for the Saniya Resort website experience." };

const icons: Record<string, LucideIcon> = { waves: Waves, heart: Heart, utensils: UtensilsCrossed, sparkles: Sparkles, briefcase: BriefcaseBusiness, baby: Baby, party: PartyPopper, wifi: Wifi, car: Car, sun: Sun, users: Users };

export default function FacilitiesPage() {
  return <>
    <section className="relative isolate min-h-[64svh] overflow-hidden bg-ink text-white">
      <Image src={facilityHero.src} alt={facilityHero.alt} fill priority sizes="100vw" className="object-cover" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(6,42,36,.86)_0%,rgba(6,42,36,.48)_55%,rgba(6,42,36,.12)_100%)]" />
      <div className="container-shell relative z-10 flex min-h-[64svh] items-end py-16 sm:py-24"><div className="max-w-3xl"><p className="eyebrow text-sun">The resort experience</p><h1 className="display-title mt-5 text-5xl sm:text-7xl">A little something<br /><span className="text-[#f7cf91]">for every kind of day.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-white/80 sm:text-lg">A thoughtful collection of spaces for swimming, gathering, celebrating, and making the most of time together.</p><p className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-white/55">Independent concept · details to be confirmed</p></div></div>
    </section>

    <section className="py-20 sm:py-28"><div className="container-shell"><SectionHeading eyebrow="Designed around your day" title="More than a list of amenities" body="This concept organizes the resort experience around how guests actually spend their time: moving, meeting, eating, celebrating, and settling into the easy parts in between." /><div className="mt-12 grid gap-6 lg:grid-cols-3">{facilityFeatures.map((feature, index) => <Reveal key={feature.id} delay={index * .08} className={index === 1 ? "lg:translate-y-10" : ""}><article className="group overflow-hidden rounded-[2rem] bg-surface shadow-[var(--shadow-card)]"><div className="relative aspect-[4/3] overflow-hidden"><Image src={feature.image.src} alt={feature.image.alt} fill sizes="(max-width:1024px) 100vw,33vw" className="object-cover transition duration-700 group-hover:scale-105" /></div><div className="p-6 sm:p-7"><p className="eyebrow text-coral">{feature.eyebrow}</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-tight">{feature.title}</h2><p className="mt-4 text-sm leading-6 text-muted">{feature.description}</p><Link href={feature.href} className="group/link mt-6 inline-flex items-center gap-2 font-bold text-brand">{feature.linkLabel}<ArrowRight className="size-4 transition-transform group-hover/link:translate-x-1" aria-hidden="true" /></Link></div></article></Reveal>)}</div></div></section>

    <section className="bg-surface py-20 sm:py-28"><div className="container-shell"><SectionHeading eyebrow="Amenity directory" title="Find your kind of easy" body="A practical, scannable starting point for the details guests want before they arrive. All entries below are conceptual and can be replaced with approved information." /><div className="mt-12 space-y-5">{amenityCategories.map((category, index) => { const CategoryIcon = icons[category.icon]; return <Reveal key={category.id} delay={index * .04}><section className="grid gap-6 rounded-[1.75rem] border border-black/8 bg-canvas p-6 sm:p-8 lg:grid-cols-[.7fr_1.3fr] lg:items-start"><div className="flex gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#dcece5] text-brand"><CategoryIcon aria-hidden="true" /></span><div><h2 className="font-display text-2xl font-semibold">{category.title}</h2><p className="mt-2 max-w-sm text-sm leading-6 text-muted">{category.description}</p></div></div><div className="grid gap-3 sm:grid-cols-2">{category.items.map(item => { const ItemIcon = icons[item.icon]; return <div key={item.name} className="rounded-2xl bg-surface p-4"><ItemIcon className="size-5 text-brand" aria-hidden="true" /><h3 className="mt-3 font-bold">{item.name}</h3><p className="mt-1 text-sm leading-5 text-muted">{item.description}</p></div>; })}</div></section></Reveal>; })}</div></div></section>

    <section className="py-20 sm:py-28"><div className="container-shell grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><Reveal><p className="eyebrow text-brand">Build your own day</p><h2 className="display-title mt-4 max-w-2xl text-4xl sm:text-6xl">Stay close to the things that bring everyone in.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-muted">Start with a room, add a pool day, make space for a meal, and leave a little room for the unexpected.</p></Reveal><Reveal delay={.1} className="rounded-[2rem] bg-[#dcece5] p-7 sm:p-9"><p className="eyebrow text-coral">Explore next</p><nav className="mt-5 grid gap-1" aria-label="Related resort experiences">{[{ href: "/pools", label: "Pools & water time" }, { href: "/dining", label: "Dining concept" }, { href: "/events", label: "Events & celebrations" }, { href: "/accommodations", label: "Accommodations" }].map(item => <Link key={item.href} href={item.href} className="group flex min-h-12 items-center justify-between border-b border-ink/10 font-bold"><span>{item.label}</span><ArrowRight className="size-4 text-brand transition-transform group-hover:translate-x-1" aria-hidden="true" /></Link>)}</nav><Link href="/booking" className="mt-8 inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3.5 font-bold text-white transition hover:bg-brand">Plan a demo stay <ArrowRight className="size-4" aria-hidden="true" /></Link></Reveal></div></section>
  </>;
}
