"use client";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowLeft, ArrowRight, LoaderCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { FormProvider, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { bookingSchema, defaultBookingValues, type BookingForm, type BookingStep } from "@/data/booking";
import { AccommodationStep, AddOnsStep, Confirmation, DatesStep, DetailsStep, GuestsStep, SummaryStep } from "@/components/booking/booking-steps";

const steps = ["Dates", "Accommodation", "Guests", "Add-ons", "Your details", "Summary"] as const;
type WizardProps = { initialValues: Partial<BookingForm> };

export function BookingWizard({ initialValues }: WizardProps) {
  const methods = useForm<BookingForm>({ resolver: zodResolver(bookingSchema), defaultValues: { ...defaultBookingValues(), ...initialValues }, mode: "onTouched" });
  const [step, setStep] = useState<BookingStep>(0); const [submitted, setSubmitted] = useState(false); const [reference, setReference] = useState(""); const [isSubmitting, setIsSubmitting] = useState(false); const reduceMotion = useReducedMotion();
  const { trigger, getValues, reset } = methods;
  const fields: Record<number, (keyof BookingForm)[]> = { 0: ["checkIn", "checkOut"], 1: ["accommodationId"], 2: ["adults", "children"], 3: ["addOns"], 4: ["firstName", "lastName", "email", "phone", "acknowledgement"] };
  useEffect(() => { window.scrollTo({ top: 0, behavior: reduceMotion ? "auto" : "smooth" }); }, [step, submitted, reduceMotion]);
  const next = async () => { const valid = await trigger(fields[step] ?? []); if (!valid) return; if (step < 5) setStep((step + 1) as BookingStep); };
  const submit = async () => { const valid = await trigger(); if (!valid) return; setIsSubmitting(true); await new Promise(resolve => setTimeout(resolve, 500)); const values = getValues(); const stamp = values.checkIn.replaceAll("-", "").slice(2); setReference(`SAN-${stamp}-${values.accommodationId.slice(0, 3).toUpperCase()}`); setIsSubmitting(false); setSubmitted(true); };
  const resetBooking = () => { reset(defaultBookingValues()); setStep(0); setSubmitted(false); setReference(""); };
  if (submitted) return <Confirmation reference={reference} onReset={resetBooking}/>;
  const CurrentStep = [DatesStep, AccommodationStep, GuestsStep, AddOnsStep, DetailsStep, () => <SummaryStep onEdit={setStep}/>,][step];
  return <FormProvider {...methods}><div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_18rem] lg:gap-14"><div><nav aria-label="Booking progress" className="mb-9"><ol className="grid grid-cols-6 gap-1 sm:gap-2">{steps.map((label, index) => <li key={label}><button type="button" onClick={() => index < step && setStep(index as BookingStep)} disabled={index > step} className={`w-full text-left ${index > step ? "cursor-default opacity-45" : "cursor-pointer"}`} aria-current={step === index ? "step" : undefined}><span className={`mb-2 block h-1 rounded-full ${index <= step ? "bg-brand" : "bg-black/10"}`}/><span className="hidden text-xs font-bold sm:block">{index + 1}. {label}</span><span className="text-xs font-bold sm:hidden">{index + 1}</span></button></li>)}</ol></nav><div aria-live="polite" aria-atomic="true"><AnimatePresence mode="wait"><motion.div key={step} initial={{ opacity: 0, x: reduceMotion ? 0 : 14 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: reduceMotion ? 0 : -14 }} transition={{ duration: reduceMotion ? 0 : .22 }}><CurrentStep/></motion.div></AnimatePresence></div><div className="mt-9 flex items-center justify-between gap-4 border-t border-black/10 pt-6"><button type="button" onClick={() => setStep((step - 1) as BookingStep)} disabled={step === 0} className="inline-flex min-h-12 items-center gap-2 rounded-full px-3 font-bold text-brand disabled:invisible"><ArrowLeft className="size-4" aria-hidden="true"/>Back</button>{step < 5 ? <button type="button" onClick={next} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-brand px-6 font-bold text-white transition hover:bg-brand-dark">Continue <ArrowRight className="size-4" aria-hidden="true"/></button> : <button type="button" onClick={submit} disabled={isSubmitting} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-brand px-6 font-bold text-white transition hover:bg-brand-dark disabled:cursor-wait disabled:opacity-70">{isSubmitting ? <><LoaderCircle className="size-4 animate-spin" aria-hidden="true"/>Creating demo reference…</> : <>Confirm demo stay <ArrowRight className="size-4" aria-hidden="true"/></>}</button>}</div></div><aside className="h-fit rounded-[1.5rem] bg-surface p-5 shadow-[var(--shadow-card)] lg:sticky lg:top-28"><p className="eyebrow text-brand">Booking concept</p><h2 className="mt-3 font-display text-2xl font-semibold">A simple plan, all in one place.</h2><p className="mt-3 text-sm leading-6 text-muted">Your choices stay in this browser session while you move through the steps. No payment information is requested.</p><div className="mt-5 flex items-start gap-3 border-t border-black/10 pt-5 text-xs leading-5 text-muted"><span className="mt-1 size-2 shrink-0 rounded-full bg-sun"/>Illustrative pricing and availability only.</div></aside></div></FormProvider>;
}
