"use client";
import Image from "next/image";
import Link from "next/link";
import { addDays, format, parseISO } from "date-fns";
import { BedDouble, Check, ChevronUp, CircleCheck, Gift, Minus, Plus, Users } from "lucide-react";
import { useFormContext } from "react-hook-form";
import { accommodations } from "@/data/home";
import { addOns, calculateBookingTotal, formatDemoPrice, type BookingForm, type BookingStep } from "@/data/booking";

const errorText = (error: { message?: string } | undefined) => error?.message ? <p className="mt-1 text-sm font-semibold text-coral" role="alert">{error.message}</p> : null;

export function DatesStep() {
  const { register, formState: { errors }, watch } = useFormContext<BookingForm>(); const checkIn = watch("checkIn");
  return <div className="space-y-7"><div><p className="eyebrow text-coral">Step one</p><h2 className="display-title mt-3 text-4xl sm:text-5xl">When will you stay?</h2><p className="mt-4 max-w-xl leading-7 text-muted">Choose dates for your illustrative stay. Arrival dates begin today; departure must come after arrival.</p></div><div className="grid gap-5 sm:grid-cols-2"><label className="field-label">Arrival<input type="date" min={format(new Date(), "yyyy-MM-dd")} {...register("checkIn")} aria-invalid={!!errors.checkIn} />{errorText(errors.checkIn)}</label><label className="field-label">Departure<input type="date" min={checkIn || format(addDays(new Date(), 1), "yyyy-MM-dd")} {...register("checkOut")} aria-invalid={!!errors.checkOut} />{errorText(errors.checkOut)}</label></div></div>;
}

export function AccommodationStep() {
  const { setValue, watch, formState: { errors } } = useFormContext<BookingForm>(); const selected = watch("accommodationId"); const guests = watch("adults") + watch("children");
  return <div className="space-y-7"><div><p className="eyebrow text-coral">Step two</p><h2 className="display-title mt-3 text-4xl sm:text-5xl">Choose your space.</h2><p className="mt-4 max-w-xl leading-7 text-muted">Every option below is illustrative demo inventory. Pricing and availability are not live.</p></div><div className="grid gap-5">{accommodations.map(room => { const unavailable = guests > room.capacity; return <button type="button" key={room.id} disabled={unavailable} onClick={() => setValue("accommodationId", room.id, { shouldValidate: true })} className={`grid gap-5 rounded-[1.5rem] border-2 p-4 text-left transition sm:grid-cols-[10rem_1fr_auto] sm:items-center ${selected === room.id ? "border-brand bg-[#e9f3ee]" : "border-black/8 bg-surface hover:border-brand/50"} ${unavailable ? "cursor-not-allowed opacity-50" : ""}`} aria-pressed={selected === room.id}><div className="relative aspect-[4/3] overflow-hidden rounded-xl"><Image src={room.image.src} alt="" fill sizes="160px" className="object-cover" /></div><div><span className="eyebrow text-brand">{room.category}</span><h3 className="mt-1 font-display text-2xl font-semibold">{room.name}</h3><p className="mt-2 text-sm leading-6 text-muted">{room.summary}</p><div className="mt-3 flex flex-wrap gap-4 text-xs font-bold text-muted"><span className="flex items-center gap-1.5"><Users className="size-4 text-brand" aria-hidden="true"/>Up to {room.capacity}</span><span className="flex items-center gap-1.5"><BedDouble className="size-4 text-brand" aria-hidden="true"/>{room.beds}</span></div></div><div className="sm:text-right"><p className="font-display text-xl font-semibold">{formatDemoPrice(room.demoPricePerNight)}</p><p className="text-xs text-muted">per night · demo</p>{unavailable ? <p className="mt-2 text-xs font-bold text-coral">Over your group capacity</p> : selected === room.id ? <CircleCheck className="mt-3 size-6 text-brand sm:ml-auto" aria-label="Selected"/> : null}</div></button>; })}</div>{errorText(errors.accommodationId)}</div>;
}

function Counter({ label, name, max, value, onChange }: { label: string; name: string; max: number; value: number; onChange: (value: number) => void }) { return <div className="flex items-center justify-between rounded-2xl border border-black/10 bg-surface p-4"><div><p className="font-bold">{label}</p><p className="mt-1 text-sm text-muted">{name === "adults" ? "Ages 13 and up" : "Ages 3–12"}</p></div><div className="flex items-center gap-3"><button type="button" className="grid size-10 place-items-center rounded-full border border-black/10 bg-canvas" onClick={() => onChange(Math.max(name === "adults" ? 1 : 0, value - 1))} aria-label={`Decrease ${label}`} disabled={value <= (name === "adults" ? 1 : 0)}><Minus className="size-4" aria-hidden="true"/></button><output className="w-5 text-center font-bold" aria-label={`${value} ${label.toLowerCase()}`}>{value}</output><button type="button" className="grid size-10 place-items-center rounded-full border border-black/10 bg-canvas" onClick={() => onChange(Math.min(max, value + 1))} aria-label={`Increase ${label}`} disabled={value >= max}><Plus className="size-4" aria-hidden="true"/></button></div></div>; }

export function GuestsStep() { const { watch, setValue, formState: { errors } } = useFormContext<BookingForm>(); const room = accommodations.find(item => item.id === watch("accommodationId")); const adults = watch("adults"); const children = watch("children"); const remaining = (room?.capacity ?? 12) - adults - children; return <div className="space-y-7"><div><p className="eyebrow text-coral">Step three</p><h2 className="display-title mt-3 text-4xl sm:text-5xl">Who’s coming along?</h2><p className="mt-4 max-w-xl leading-7 text-muted">Tell us about your group. {room ? `${room.name} sleeps up to ${room.capacity}.` : "Select an accommodation to see its capacity."}</p></div><div className="space-y-3"><Counter label="Adults" name="adults" max={room?.capacity ?? 12} value={adults} onChange={value => setValue("adults", value, { shouldValidate: true })}/><Counter label="Children" name="children" max={Math.max(0, (room?.capacity ?? 12) - adults)} value={children} onChange={value => setValue("children", value, { shouldValidate: true })}/></div><p className={`text-sm font-semibold ${remaining < 0 ? "text-coral" : "text-muted"}`}>{remaining >= 0 ? `${remaining} ${remaining === 1 ? "space" : "spaces"} remaining` : "This group is over the accommodation capacity."}</p>{errorText(errors.adults)}</div>; }

export function AddOnsStep() { const { watch, setValue } = useFormContext<BookingForm>(); const selected = watch("addOns"); return <div className="space-y-7"><div><p className="eyebrow text-coral">Step four</p><h2 className="display-title mt-3 text-4xl sm:text-5xl">Add a little extra.</h2><p className="mt-4 max-w-xl leading-7 text-muted">Optional, conceptual add-ons for this demonstration. You can choose as many as you like.</p></div><div className="grid gap-4 sm:grid-cols-2">{addOns.map(item => { const active = selected.includes(item.id); return <button type="button" key={item.id} onClick={() => setValue("addOns", active ? selected.filter(id => id !== item.id) : [...selected, item.id])} className={`rounded-[1.5rem] border-2 p-5 text-left transition ${active ? "border-brand bg-[#e9f3ee]" : "border-black/8 bg-surface hover:border-brand/50"}`} aria-pressed={active}><div className="flex items-start justify-between gap-4"><span className="grid size-10 place-items-center rounded-full bg-[#dcece5] text-brand"><Gift className="size-5" aria-hidden="true"/></span>{active ? <Check className="size-5 text-brand" aria-label="Selected"/> : null}</div><h3 className="mt-5 font-display text-2xl font-semibold">{item.name}</h3><p className="mt-2 text-sm leading-6 text-muted">{item.description}</p><p className="mt-4 text-sm font-bold">{formatDemoPrice(item.price)} <span className="font-normal text-muted">· {item.billing}</span></p></button>; })}</div></div>; }

export function DetailsStep() { const { register, formState: { errors } } = useFormContext<BookingForm>(); return <div className="space-y-7"><div><p className="eyebrow text-coral">Step five</p><h2 className="display-title mt-3 text-4xl sm:text-5xl">Tell us who to expect.</h2><p className="mt-4 max-w-xl leading-7 text-muted">These details stay in this demo experience and are not sent anywhere.</p></div><div className="grid gap-5 sm:grid-cols-2"><label className="field-label">First name<input type="text" autoComplete="given-name" {...register("firstName")} aria-invalid={!!errors.firstName}/>{errorText(errors.firstName)}</label><label className="field-label">Last name<input type="text" autoComplete="family-name" {...register("lastName")} aria-invalid={!!errors.lastName}/>{errorText(errors.lastName)}</label><label className="field-label">Email address<input type="email" autoComplete="email" inputMode="email" {...register("email")} aria-invalid={!!errors.email}/>{errorText(errors.email)}</label><label className="field-label">Phone number<input type="tel" autoComplete="tel" inputMode="tel" {...register("phone")} aria-invalid={!!errors.phone}/>{errorText(errors.phone)}</label><label className="field-label sm:col-span-2">Special requests <span className="font-normal text-muted">(optional)</span><textarea rows={4} autoComplete="off" {...register("specialRequests")} placeholder="Anything you’d like the host team to know?"/></label></div><label className="flex items-start gap-3 rounded-2xl bg-[#fff5dc] p-4 text-sm leading-6"><input type="checkbox" className="mt-1 size-4 accent-[var(--brand)]" {...register("acknowledgement")} /> <span>I understand this is a demonstration only. No real reservation, charge, or communication will be created.</span></label>{errorText(errors.acknowledgement)}</div>; }

export function SummaryStep({ onEdit }: { onEdit: (step: BookingStep) => void }) { const { watch } = useFormContext<BookingForm>(); const values = watch(); const room = accommodations.find(item => item.id === values.accommodationId); const totals = calculateBookingTotal(values); return <div className="space-y-7"><div><p className="eyebrow text-coral">Step six</p><h2 className="display-title mt-3 text-4xl sm:text-5xl">Review your stay.</h2><p className="mt-4 max-w-xl leading-7 text-muted">Everything below uses illustrative demo pricing. No payment details are collected.</p></div><div className="divide-y divide-black/10 rounded-[1.5rem] bg-surface px-5 shadow-[var(--shadow-card)]"><SummaryRow label="Dates" value={`${format(parseISO(values.checkIn), "MMM d, yyyy")} – ${format(parseISO(values.checkOut), "MMM d, yyyy")} · ${totals.nights} ${totals.nights === 1 ? "night" : "nights"}`} onEdit={() => onEdit(0)}/><SummaryRow label="Accommodation" value={room?.name ?? "Not selected"} onEdit={() => onEdit(1)}/><SummaryRow label="Guests" value={`${values.adults} adults${values.children ? `, ${values.children} children` : ""}`} onEdit={() => onEdit(2)}/><SummaryRow label="Add-ons" value={values.addOns.length ? values.addOns.map(id => addOns.find(item => item.id === id)?.name).join(", ") : "None selected"} onEdit={() => onEdit(3)}/><SummaryRow label="Guest" value={`${values.firstName} ${values.lastName}`} onEdit={() => onEdit(4)}/></div><div className="rounded-[1.5rem] border border-black/10 bg-[#e9f3ee] p-5"><PriceLine label={`${room?.name ?? "Accommodation"} × ${totals.nights} nights`} value={formatDemoPrice(totals.roomTotal)}/>{values.addOns.length ? <PriceLine label="Optional add-ons" value={formatDemoPrice(totals.addOnTotal)}/> : null}<PriceLine label="Demo service fee (8%)" value={formatDemoPrice(totals.fees)}/><div className="mt-4 flex justify-between border-t border-black/10 pt-4 text-lg font-bold"><span>Illustrative total</span><span>{formatDemoPrice(totals.total)}</span></div></div></div>; }
function SummaryRow({ label, value, onEdit }: { label: string; value: string; onEdit: () => void }) { return <div className="flex items-start justify-between gap-4 py-4"><div><p className="text-xs font-bold uppercase tracking-wider text-muted">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div><button type="button" onClick={onEdit} className="inline-flex items-center gap-1 text-sm font-bold text-brand">Edit <ChevronUp className="size-4" aria-hidden="true"/></button></div>; }
function PriceLine({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 py-1.5 text-sm"><span>{label}</span><span className="font-bold">{value}</span></div>; }

export function Confirmation({ reference, onReset }: { reference: string; onReset: () => void }) { return <div className="py-8 text-center sm:py-16"><span className="mx-auto grid size-16 place-items-center rounded-full bg-[#dcece5] text-brand"><CircleCheck className="size-9" aria-hidden="true"/></span><p className="eyebrow mt-7 text-coral">Demo confirmation</p><h2 className="display-title mt-3 text-4xl sm:text-6xl">Your stay is mapped out.</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-muted">Reference <strong className="text-ink">{reference}</strong> has been created for this demonstration.</p><div className="mx-auto mt-8 max-w-xl rounded-2xl bg-[#fff5dc] p-5 text-sm leading-6">No real booking, charge, or communication occurred. This independent website concept does not connect to live resort systems.</div><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/" className="rounded-full bg-brand px-6 py-3.5 font-bold text-white transition hover:bg-brand-dark">Return home</Link><button type="button" onClick={onReset} className="rounded-full border border-black/10 bg-surface px-6 py-3.5 font-bold transition hover:border-brand">Begin another booking</button></div></div>; }
