"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { addDays, format } from "date-fns";
import { ArrowRight, CalendarDays, Users } from "lucide-react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { z } from "zod";
const bookingSchema=z.object({checkIn:z.string().min(1,"Choose an arrival date"),checkOut:z.string().min(1,"Choose a departure date"),guests:z.coerce.number().int().min(1).max(12)}).refine(data=>new Date(data.checkOut)>new Date(data.checkIn),{message:"Departure must be after arrival",path:["checkOut"]});
type BookingInput=z.input<typeof bookingSchema>;
type BookingOutput=z.output<typeof bookingSchema>;
export function QuickBooking(){const router=useRouter();const today=new Date();const min=format(today,"yyyy-MM-dd");const{register,handleSubmit,formState:{errors}}=useForm<BookingInput,unknown,BookingOutput>({resolver:zodResolver(bookingSchema),defaultValues:{checkIn:format(addDays(today,7),"yyyy-MM-dd"),checkOut:format(addDays(today,9),"yyyy-MM-dd"),guests:2}});const submit=(values:BookingOutput)=>{const query=new URLSearchParams({checkIn:values.checkIn,checkOut:values.checkOut,guests:String(values.guests)});router.push(`/booking?${query}`)};return <form onSubmit={handleSubmit(submit)} className="relative z-10 mt-8 rounded-[1.75rem] bg-surface p-3 text-ink shadow-[var(--shadow-soft)]" aria-label="Check stay availability"><div className="grid gap-2 md:grid-cols-[1fr_1fr_.7fr_auto]">{(["checkIn","checkOut"] as const).map((field,index)=><label key={field} className="rounded-2xl px-4 py-3 transition focus-within:bg-canvas"><span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-muted"><CalendarDays className="size-4 text-brand" aria-hidden="true"/>{index?"Departure":"Arrival"}</span><input type="date" min={min} {...register(field)} className="mt-1 w-full bg-transparent text-sm font-bold outline-none"/>{errors[field]?<span className="text-xs text-coral">{errors[field]?.message}</span>:null}</label>)}<label className="rounded-2xl px-4 py-3 transition focus-within:bg-canvas"><span className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-muted"><Users className="size-4 text-brand" aria-hidden="true"/>Guests</span><select {...register("guests")} className="mt-1 w-full bg-transparent text-sm font-bold outline-none">{Array.from({length:12},(_,index)=>index+1).map(count=><option key={count} value={count}>{count} {count===1?"guest":"guests"}</option>)}</select></label><button type="submit" className="group flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-brand px-6 font-bold text-white transition hover:bg-brand-dark md:min-h-full">Explore stays <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" aria-hidden="true"/></button></div></form>}
