export type ImageAsset = { src: string; alt: string };
export type DiningExperience = { id: string; title: string; description: string; moment: string };
export type DemoMenuItem = { id: string; name: string; description: string; demoPrice: number; serving: string };
export type EventType = { id: string; label: string };
export type EventSetting = { id: string; name: string; description: string; planningNote: string; image: ImageAsset };
export type EventPlanningStep = { title: string; description: string };
export type Accommodation = {
  id: string;
  name: string;
  category: "Room" | "Cottage" | "Villa";
  summary: string;
  description: string;
  capacity: number;
  beds: string;
  size: string;
  stayNote: string;
  image: ImageAsset;
  gallery: ImageAsset[];
  amenities: string[];
  demoPricePerNight: number;
  featured?: boolean;
};
export type Experience = { id: string; title: string; description: string; image: ImageAsset; tag: string };
export type PackageOffer = {
  id: string;
  category: "Day-use" | "Overnight" | "Family" | "Celebration" | "Group";
  name: string;
  description: string;
  badge: string;
  inclusions: string[];
  limitations: string[];
  suitableFor: string;
  demoStartingPrice: number;
  priceUnit: string;
  action: "booking" | "accommodations" | "events" | "contact";
  bookingQuery?: { accommodation?: string; guests?: number };
};
export type ContactMethod = { label: string; value: string; href?: string; note: string; icon: "mail" | "phone" | "message" };
export type PlanningQuestion = { question: string; answer: string };
export type GalleryCategory = "All" | "Stay" | "Swim" | "Dine" | "Celebrate" | "Resort spaces";
export type GalleryItem = ImageAsset & { id: string; category: Exclude<GalleryCategory, "All">; label: string; description: string };
export type AmenityCategory = {
  id: string;
  title: string;
  description: string;
  icon: "waves" | "heart" | "utensils" | "sparkles" | "briefcase";
  items: { name: string; description: string; icon: "waves" | "baby" | "utensils" | "party" | "wifi" | "car" | "sun" | "users" | "sparkles" }[];
};
export type FacilityFeature = { id: string; eyebrow: string; title: string; description: string; image: ImageAsset; href: string; linkLabel: string; imagePosition?: string };
export type PoolZone = ImageAsset & { id: string; name: string; type: string; description: string; mood: string; guidance: string; icon: "waves" | "baby" | "sun" };
