import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BedDouble, Check, MapPin, Sparkles, Sun, Users, UtensilsCrossed, Waves } from "lucide-react";
import { QuickBooking } from "@/components/booking/quick-booking";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";
import { accommodations, experiences, gallery, heroImage, packages } from "@/data/home";

export default function Home(){return <>
  <section className="relative isolate min-h-[calc(100svh-5rem)] overflow-hidden bg-ink text-white">
    <Image src={heroImage.src} alt={heroImage.alt} fill priority sizes="100vw" className="object-cover"/>
    <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(6,42,36,.86)_0%,rgba(6,42,36,.5)_50%,rgba(6,42,36,.14)_100%)]"/>
    <div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(6,42,36,.58)_0%,transparent_48%)]"/>
    <div className="container-shell relative z-10 flex min-h-[calc(100svh-5rem)] flex-col justify-center py-14 sm:py-20">
      <div className="max-w-3xl"><p className="eyebrow text-sun">Your easygoing escape</p><h1 className="display-title mt-5 text-5xl sm:text-7xl lg:text-[5.7rem]">More time together,<br/><span className="text-[#f7cf91]">more stories to keep.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-white/80 sm:text-lg">A welcoming tropical resort concept for family stays, refreshing pool days, shared meals, and celebrations that feel like you.</p></div>
      <div className="max-w-5xl"><QuickBooking/><p className="mt-3 pl-3 text-xs text-white/60">Demo availability · No payment or live reservation is processed</p></div>
    </div>
  </section>

  <section className="overflow-hidden py-20 sm:py-28"><div className="container-shell grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr] lg:gap-20"><Reveal><p className="eyebrow text-coral">Come as you are</p><h2 className="display-title mt-4 text-4xl sm:text-6xl">The kind of place where everyone settles in.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-muted">This independent redesign imagines Saniya as a friendly, flexible home base: polished enough for a special occasion, relaxed enough for dripping slippers and one more swim.</p><div className="mt-8 flex flex-wrap gap-3">{[{icon:Waves,label:"Pool days"},{icon:UtensilsCrossed,label:"Shared meals"},{icon:Sparkles,label:"Celebrations"}].map(({icon:Icon,label})=><span key={label} className="inline-flex items-center gap-2 rounded-full border border-black/8 bg-surface px-4 py-2 text-sm font-bold shadow-sm"><Icon className="size-4 text-brand" aria-hidden="true"/>{label}</span>)}</div></Reveal><Reveal delay={.1} className="relative"><div className="relative ml-auto aspect-[4/3] max-w-2xl overflow-hidden rounded-[2.5rem]"><Image src={gallery[0].src} alt={gallery[0].alt} fill sizes="(max-width:1024px) 100vw,55vw" className="object-cover"/></div><div className="absolute -bottom-6 -left-3 rounded-3xl bg-sun p-5 shadow-[var(--shadow-card)] sm:left-6"><Sun className="size-7" aria-hidden="true"/><p className="mt-2 max-w-32 font-display text-xl font-semibold leading-tight">Made for sunny days</p></div></Reveal></div></section>

  <section className="bg-surface py-20 sm:py-28"><div className="container-shell"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionHeading eyebrow="Find your space" title="Room for every kind of getaway" body="Thoughtful demo accommodation types show how real inventory can be presented clearly, without inventing live rates or availability."/><Link href="/accommodations" className="group inline-flex items-center gap-2 font-bold text-brand">See all stays <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" aria-hidden="true"/></Link></div><div className="mt-12 grid gap-6 md:grid-cols-3">{accommodations.map((room,index)=><Reveal key={room.id} delay={index*.07}><article className="group overflow-hidden rounded-[1.75rem] bg-canvas shadow-[var(--shadow-card)]"><div className="relative aspect-[4/3] overflow-hidden"><Image src={room.image.src} alt={room.image.alt} fill sizes="(max-width:768px) 100vw,33vw" className="object-cover transition duration-700 group-hover:scale-105"/><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1.5 text-xs font-bold backdrop-blur">{room.category}</span></div><div className="p-6"><h3 className="font-display text-2xl font-semibold tracking-tight">{room.name}</h3><p className="mt-3 text-sm leading-6 text-muted">{room.summary}</p><div className="mt-5 flex gap-5 border-t border-black/8 pt-4 text-xs font-bold text-muted"><span className="flex items-center gap-1.5"><Users className="size-4 text-brand" aria-hidden="true"/>Up to {room.capacity}</span><span className="flex items-center gap-1.5"><BedDouble className="size-4 text-brand" aria-hidden="true"/>{room.beds}</span></div></div></article></Reveal>)}</div></div></section>

  <section className="py-20 sm:py-28"><div className="container-shell"><SectionHeading eyebrow="Your day, your pace" title="Do a lot. Or wonderfully little." body="From poolside afternoons to meaningful celebrations, every experience has a distinct place in the journey." align="center"/><div className="mt-12 grid gap-5 lg:grid-cols-3">{experiences.map((item,index)=><Reveal key={item.id} delay={index*.08}><Link href={`/${item.tag.toLowerCase()}`} className="group relative block min-h-[28rem] overflow-hidden rounded-[2rem] text-white"><Image src={item.image.src} alt={item.image.alt} fill sizes="(max-width:1024px) 100vw,33vw" className="object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-ink/90 via-ink/15 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7"><span className="eyebrow text-sun">{item.tag}</span><h3 className="mt-3 font-display text-3xl font-semibold tracking-tight">{item.title}</h3><p className="mt-3 text-sm leading-6 text-white/75">{item.description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold">Explore <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" aria-hidden="true"/></span></div></Link></Reveal>)}</div></div></section>

  <section className="bg-[#dcece5] py-20 sm:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><Reveal><SectionHeading eyebrow="Offers, made simple" title="A better reason to stay a little longer" body="These illustrative packages demonstrate offer discovery and can be replaced with approved, date-bound promotions later."/><Link href="/packages" className="mt-8 inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3.5 font-bold text-white transition hover:bg-brand">View all offers <ArrowRight className="size-4" aria-hidden="true"/></Link></Reveal><div className="grid gap-4">{packages.map((offer,index)=><Reveal key={offer.id} delay={index*.08}><article className="rounded-[1.75rem] bg-surface p-6 shadow-[var(--shadow-card)] sm:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="eyebrow text-coral">{offer.badge}</span><h3 className="mt-2 font-display text-3xl font-semibold tracking-tight">{offer.name}</h3></div><span className="rounded-full bg-canvas px-3 py-1.5 text-xs font-bold text-muted">Demo package</span></div><p className="mt-4 max-w-xl text-sm leading-6 text-muted">{offer.description}</p><ul className="mt-5 flex flex-wrap gap-x-5 gap-y-2">{offer.inclusions.map(item=><li key={item} className="flex items-center gap-2 text-sm font-semibold"><Check className="size-4 text-brand" aria-hidden="true"/>{item}</li>)}</ul></article></Reveal>)}</div></div></section>

  <section className="bg-ink py-20 text-white sm:py-28"><div className="container-shell"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow text-sun">A glimpse of Saniya</p><h2 className="display-title mt-4 max-w-xl text-4xl sm:text-6xl">See yourself in the moment.</h2></div><Link href="/gallery" className="group inline-flex items-center gap-2 font-bold">Open the gallery <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" aria-hidden="true"/></Link></div><div className="mt-12 grid grid-cols-2 gap-3 md:grid-cols-4">{gallery.map((item,index)=><Reveal key={item.id} delay={index*.06} className={index===0?"col-span-2 row-span-2":""}><figure className={`group relative overflow-hidden rounded-3xl ${index===0?"aspect-square md:aspect-auto md:h-full":"aspect-square"}`}><Image src={item.src} alt={item.alt} fill sizes={index===0?"(max-width:768px) 100vw,50vw":"(max-width:768px) 50vw,25vw"} className="object-cover transition duration-700 group-hover:scale-105"/><figcaption className="absolute bottom-3 left-3 rounded-full bg-ink/65 px-3 py-1 text-xs font-bold backdrop-blur">{item.category}</figcaption></figure></Reveal>)}</div></div></section>

  <section className="py-20 sm:py-28"><div className="container-shell"><Reveal><div className="relative overflow-hidden rounded-[2.5rem] bg-coral px-6 py-14 text-center text-white sm:px-12 sm:py-20"><div className="absolute -left-20 -top-24 size-72 rounded-full border-[48px] border-white/10"/><div className="absolute -bottom-24 -right-16 size-64 rounded-full bg-sun/30"/><MapPin className="relative mx-auto size-8" aria-hidden="true"/><p className="eyebrow relative mt-5 text-white/70">Plan the easy escape</p><h2 className="display-title relative mx-auto mt-4 max-w-3xl text-4xl sm:text-6xl">Good times are closer than you think.</h2><p className="relative mx-auto mt-5 max-w-xl leading-7 text-white/80">Explore the location concept, send an inquiry, or start a demo booking in just a few steps.</p><div className="relative mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/booking" className="rounded-full bg-white px-7 py-4 font-bold text-ink transition hover:bg-canvas">Start a booking</Link><Link href="/contact" className="rounded-full border border-white/30 px-7 py-4 font-bold transition hover:bg-white/10">Contact & location</Link></div></div></Reveal></div></section>
</>}
