"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { contactInquirySchema, contactTopics, emptyContactInquiry, type ContactInquiryValues } from "@/lib/contact-inquiry";

function Field({ id, label, error, optional, children }: { id: string; label: string; error?: string; optional?: boolean; children: ReactNode }) {
  return <div><label htmlFor={id} className="field-label">{label}{optional && <span className="font-normal text-muted"> (optional)</span>}{children}</label>{error && <p id={`${id}-error`} className="mt-2 text-sm font-semibold text-red-800" role="alert">{error}</p>}</div>;
}

export function ContactForm({ initialTopic }: { initialTopic?: string }) {
  const validTopic = contactTopics.includes(initialTopic as typeof contactTopics[number]) ? initialTopic as typeof contactTopics[number] : "Something else";
  const { register, handleSubmit, reset, setFocus, formState: { errors, isSubmitting } } = useForm<ContactInquiryValues>({ resolver: zodResolver(contactInquirySchema), defaultValues: { ...emptyContactInquiry, topic: validTopic }, mode: "onTouched" });
  const [sent, setSent] = useState<ContactInquiryValues | null>(null); const successHeading = useRef<HTMLHeadingElement>(null); const resetFocus = useRef(false);
  useEffect(() => { if (sent) successHeading.current?.focus(); else if (resetFocus.current) { setFocus("topic"); resetFocus.current = false; } }, [sent, setFocus]);
  const props = (key: keyof ContactInquiryValues) => ({ id: `contact-${key}`, "aria-invalid": Boolean(errors[key]), "aria-describedby": errors[key] ? `contact-${key}-error` : undefined });
  if (sent) return <div className="rounded-[2rem] bg-surface p-6 shadow-[var(--shadow-card)] sm:p-8"><p className="eyebrow text-brand">Local demo complete</p><h2 ref={successHeading} tabIndex={-1} className="mt-3 font-display text-3xl">Your message preview is ready.</h2><p role="status" className="mt-4 leading-7">Nothing was sent or persisted. No one will contact you from this independent concept.</p><dl className="mt-6 rounded-2xl bg-canvas p-5 text-sm"><div><dt className="text-muted">Topic</dt><dd className="mt-1 font-bold">{sent.topic}</dd></div><div className="mt-4"><dt className="text-muted">Message preview</dt><dd className="mt-1 whitespace-pre-wrap leading-6">{sent.message}</dd></div></dl><button type="button" onClick={() => { reset({ ...emptyContactInquiry, topic: validTopic }); resetFocus.current = true; setSent(null); }} className="mt-7 min-h-12 rounded-full bg-brand px-6 py-3 font-bold text-white hover:bg-brand-dark">Send another message</button></div>;
  return <form noValidate onSubmit={handleSubmit(async values => { await new Promise(resolve => setTimeout(resolve, 550)); setSent(values); })} aria-busy={isSubmitting} className="rounded-[2rem] bg-surface p-6 shadow-[var(--shadow-card)] sm:p-8"><h2 className="font-display text-3xl">Put your planning question into words.</h2><p className="mt-3 text-sm leading-6 text-muted">Demo form only. Use sample details; nothing is sent, stored, or connected to a real resort.</p><fieldset disabled={isSubmitting} className="mt-7 space-y-5 disabled:opacity-65"><legend className="sr-only">Contact details and message</legend><Field id="contact-topic" label="Inquiry topic" error={errors.topic?.message}><select {...register("topic")} {...props("topic")}>{contactTopics.map(topic => <option key={topic} value={topic}>{topic}</option>)}</select></Field><div className="grid gap-5 sm:grid-cols-2"><Field id="contact-name" label="Name" error={errors.name?.message}><input autoComplete="name" maxLength={100} {...register("name")} {...props("name")} /></Field><Field id="contact-email" label="Email" error={errors.email?.message}><input type="email" autoComplete="email" inputMode="email" maxLength={254} {...register("email")} {...props("email")} /></Field></div><Field id="contact-phone" label="Phone" optional error={errors.phone?.message}><input type="tel" autoComplete="tel" inputMode="tel" maxLength={40} {...register("phone")} {...props("phone")} /></Field><Field id="contact-message" label="Message" error={errors.message?.message}><textarea rows={5} maxLength={2000} {...register("message")} {...props("message")} /></Field><button type="submit" className="min-h-12 w-full rounded-full bg-brand px-6 py-3 font-bold text-white hover:bg-brand-dark disabled:cursor-wait">{isSubmitting ? "Preparing local preview…" : "Preview demo message"}</button></fieldset><p role="status" aria-live="polite" className="mt-3 text-sm text-muted">{isSubmitting ? "Preparing your message locally. Nothing is being sent." : "No live availability, response, or follow-up is created."}</p></form>;
}
