import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Baby, Check, Info, Sun, Waves } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { poolGallery, poolHero, poolZones } from "@/data/pools";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata(
  "/pools",
  "Pools",
  "Explore a conceptual pool experience for swimming, play, and slower afternoons in this independent Saniya Resort portfolio concept.",
);
const icons: Record<string, LucideIcon> = { waves: Waves, baby: Baby, sun: Sun };

export default function PoolsPage() {
  return <>
    <section className="relative isolate min-h-[68svh] overflow-hidden bg-ink text-white"><Image src={poolHero.src} alt={poolHero.alt} fill preload sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(6,42,36,.82)_0%,rgba(6,42,36,.35)_56%,rgba(6,42,36,.08)_100%)]" /><div className="absolute inset-0 bg-gradient-to-t from-ink/65 via-transparent to-transparent" /><div className="container-shell relative z-10 flex min-h-[68svh] items-end py-16 sm:py-24"><div className="max-w-3xl"><p className="eyebrow text-sun">Water time</p><h1 className="display-title mt-5 text-5xl sm:text-7xl">Find your<br /><span className="text-[#f7cf91]">perfect splash.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-white/80 sm:text-lg">A pool day with room for big energy, small discoveries, and the quiet luxury of nowhere else to be.</p><p className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-white/55">Conceptual pool experience · subject to confirmation</p></div></div></section>

    <section className="py-20 sm:py-28"><div className="container-shell"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionHeading eyebrow="Three ways to swim" title="Choose the mood, keep the memories" body="These imagined pool zones demonstrate how future approved facilities could be introduced to guests. They do not confirm that these exact facilities exist." /><span className="inline-flex w-fit items-center gap-2 rounded-full bg-[#dcece5] px-4 py-2 text-xs font-bold text-brand"><Waves className="size-4" aria-hidden="true" /> All zones are conceptual</span></div><div className="mt-12 grid gap-6 lg:grid-cols-3">{poolZones.map((zone, index) => { const Icon = icons[zone.icon]; return <Reveal key={zone.id} delay={index * .08}><article className="group flex h-full flex-col overflow-hidden rounded-[2rem] bg-surface shadow-[var(--shadow-card)]"><div className="relative aspect-[4/3] overflow-hidden"><Image src={zone.src} alt={zone.alt} fill sizes="(max-width:1024px) 100vw,33vw" className="object-cover transition duration-700 group-hover:scale-105" /><span className="absolute left-4 top-4 inline-flex items-center gap-2 rounded-full bg-white/90 px-3 py-1.5 text-xs font-bold backdrop-blur"><Icon className="size-3.5 text-brand" aria-hidden="true" />{zone.type}</span></div><div className="flex flex-1 flex-col p-6 sm:p-7"><p className="eyebrow text-coral">{zone.mood}</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-tight">{zone.name}</h2><p className="mt-4 text-sm leading-6 text-muted">{zone.description}</p><div className="mt-auto flex gap-2 border-t border-black/8 pt-5"><Info className="mt-0.5 size-4 shrink-0 text-brand" aria-hidden="true" /><p className="text-xs leading-5 text-muted">{zone.guidance}</p></div></div></article></Reveal>; })}</div></div></section>

    <section className="bg-ink py-20 text-white sm:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><Reveal><SectionHeading tone="dark" eyebrow="A gentler pool day" title="A few good things to know" body="Water spaces work best when everyone has room to enjoy them. This generic guest guidance is a placeholder for the resort’s approved safety information." /><ul className="mt-8 space-y-4 text-sm leading-6 text-white/75"><li className="flex gap-3"><Check className="mt-1 size-4 shrink-0 text-sun" aria-hidden="true" />Please follow posted signs and any instructions from on-site team members.</li><li className="flex gap-3"><Check className="mt-1 size-4 shrink-0 text-sun" aria-hidden="true" />Children should remain within a responsible adult’s reach and supervision.</li><li className="flex gap-3"><Check className="mt-1 size-4 shrink-0 text-sun" aria-hidden="true" />Use care on wet surfaces and choose swimming areas suitable for your group.</li></ul></Reveal><div className="grid grid-cols-2 gap-3 sm:gap-5">{poolGallery.map((image, index) => <Reveal key={image.src} delay={index * .08} className={index === 0 ? "col-span-2" : ""}><figure className={`relative overflow-hidden rounded-[1.5rem] ${index === 0 ? "aspect-[16/8]" : "aspect-square"}`}><Image src={image.src} alt={image.alt} fill sizes={index === 0 ? "(max-width:768px) 100vw,60vw" : "(max-width:768px) 50vw,30vw"} className="object-cover" /><figcaption className="absolute bottom-3 left-3 rounded-full bg-ink/65 px-3 py-1 text-xs font-bold backdrop-blur">{index === 0 ? "The water story" : "Poolside moment"}</figcaption></figure></Reveal>)}</div></div></section>

    <section className="py-20 sm:py-28"><div className="container-shell"><div className="rounded-[2.5rem] bg-coral px-6 py-14 text-center text-white sm:px-12 sm:py-20"><p className="eyebrow text-white/70">Make it a day</p><h2 className="display-title mx-auto mt-4 max-w-3xl text-4xl sm:text-6xl">Ready when your group is.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-white/80">Start with a conceptual stay or send an inquiry about a future day-visit experience. Availability, access, and rates are placeholders for now.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/booking" className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-7 py-4 font-bold text-ink transition hover:bg-canvas">Start a demo booking <ArrowRight className="size-4" aria-hidden="true" /></Link><Link href="/contact" className="rounded-full border border-white/30 px-7 py-4 font-bold transition hover:bg-white/10">Ask about a day visit</Link></div></div></div></section>
  </>;
}
